/*
 * Copyright (C) 2014 Benito Palacios Sánchez
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

package guitetris;

import data.Bloque;
import data.Escenario;
import data.Figura;
import data.FiguraFactory;
import data.Punto;
import data.TipoBloque;
import java.awt.Color;
import java.awt.Graphics;

/**
 * Componente con la cuenta de puntos y niveles.
 * 
 * @author Benito Palacios Sánchez
 */
public class Marcador extends javax.swing.JPanel {  
    private static final int LongPuntos = 4;
    private static final int LongNivel  = 2;
    private static final int TamanoBloque = 5;
    private static final Punto PosicionPuntos = new Punto(20, 10);
    private static final Punto PosicionNivel = new Punto(41, 50);
    
    private Escenario escenario;
    
    /**
     * Crea un nuevo componente.
     */
    public Marcador() {
        initComponents();
    }

    /**
     * Establece el escenario.
     * 
     * @param escenario Escenario.
     */
    public void setEscenario(final Escenario escenario) {
        this.escenario = escenario;
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        if (escenario == null)
            return;
        
        // Pinta los puntos.
        int puntos = escenario.getFilasCompletas() * EscenarioPanel.GetPuntosPorFilas();
        this.paintNumber(g, puntos, LongPuntos, PosicionPuntos);
        
        // Pinta el nivel
        int nivel = escenario.getFilasCompletas() / EscenarioPanel.GetFilasPorNivel();
        this.paintNumber(g, nivel, LongNivel, PosicionNivel);
    }
    
    /**
     * Pinta un número como figura.
     * 
     * @param g Utilidad para pintar.
     * @param num Número a pintar.
     * @param len Número de cifras a pintar.
     * @param pos Posición del número.
     */
    private void paintNumber(Graphics g, int num, int len, Punto pos) {
        for (int i = 0; i < len; i++) {
            double factor = (int)Math.pow(10, len - (i + 1));
            int digit = (int)(num / factor);
            num %= factor;
            
            Punto figPos = pos.offset((TamanoBloque * Figura.GetInitSizeX() + 1) * i, 0);
            Figura figura = FiguraFactory.getNumber(figPos, Color.yellow, digit);
            this.paintFigura(g, figura);
        }
    }
    
    /**
     * Pinta una figura.
     * 
     * @param g Utilidad de gráficos.
     * @param fig Figura a pintar.
     */
    private void paintFigura(Graphics g, Figura fig) {
        Punto pos = fig.getLocation();
        for (int c = 0; c < fig.getNumColumns(); c++) {
            for (int f = 0; f < fig.getNumRows(); f++) {
                Bloque bloque = fig.getBloque(f, c);
                if (bloque.getTipo() == TipoBloque.VACIO)
                    continue;
                
                int x = pos.getCoordX() + c * TamanoBloque;
                int y = pos.getCoordY() + f * TamanoBloque;
                
                // Pinta el bloque
                g.setColor(bloque.getColor());
                g.fillRect(x, y, TamanoBloque, TamanoBloque);
                
               // Pinta el borde
                g.setColor(Color.BLACK);
                g.drawRect(x, y, TamanoBloque, TamanoBloque);  
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
